name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    name: C#
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ./c#
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.100-rc.1.21458.32

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: csharp

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          flags: c#