name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    name: Javascript
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ./javascript
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Installling dependencies
        run: npm install

      - name: ESLint check
        run: npx eslint --ignore-path .gitignore .

      - name: Prettier check
        run: npx prettier --check --ignore-path .gitignore .

      - name: Test
        run: npm run test

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
      
      - name: Send coverage report to Codecov
        uses: codecov/codecov-action@v2

