name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ./javascript
    steps:
      

