name: Ruby

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ./ruby
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5.5
        bundler-cache: true

    - name: Run the default task
      run: bundle exec rake
    
    - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          flags: ruby
